### ISSUE TITLE
Dupilicate declaration for requirement file

### ISSUE THREAD

**Issue by samho** [stankevich/puppet-python#112]
I try to do below steps:
1. Get the requirement file from master server, and save to /tmp/ directory 
2. Create the virtualenv and install package with the requirement file which has been saved in /tmp directory.

But when I try to so,  there is always an error appeared, it shows as below:
Error: Failed to apply catalog: Duplicate declaration: File[/tmp/requirement.txt] is already declared in file /etc/puppet/modules/general/manifests/init.pp:7; cannot redeclare at /etc/puppet/modules/python/manifests/requirements.pp:98

it means "path parameter" of file resource and "requirements parameter" of python::virtualenv  cannot be same, but this is not make sense, please fix it.

**Comment by shivapoudel** [comment]
@rcmachado Thank you for the explanation :)
