### ISSUE TITLE
Manage compilers?

### ISSUE THREAD

**Issue by poikilotherm** [stankevich/puppet-python#118]
Hi there,

when you use virtualenvs, it might be necessary to compile native extensions for python inside it (e.g. numpy/matplotlib).

Would it be of interest to manage installation of gcc/g++/gfortran for the virtualenv?

I would implement such thing, as I need it myself... ;)

**Comment by ghoneycutt** [comment]
@poikilotherm @igalic If compilers are necessary, modules such as this should not try to manage that, instead we should include a module that handles those compilers such as puppetlabs/gcc. Happy to include a third party module as needed.
