### ISSUE TITLE
New Feature: Pip installing specific version/tag out of VCS?

### ISSUE THREAD

**Issue by robusto** [stankevich/puppet-python#149]
I don't believe installing specific versions/tags out of the various version control systems (git, hq, svn, etc.) appears to be supported. Please correct me if I have missed something. Looks like the "ensure" logic is specific to Pypi.

[Spec here](http://pip.readthedocs.org/en/latest/reference/pip_install.html#vcs-support)

I started a fork for this, but wanted to make sure this was going in the right direction: [robusto/puppet-python](https://github.com/robusto/puppet-python/blob/master/manifests/pip.pp#L157)

**Comment by shivapoudel** [comment]
No feedback xD
