### ISSUE TITLE
python::pip downgrade to older versions fails

### ISSUE THREAD

**Issue by adc-jdiep** [stankevich/puppet-python#150]
Trying to downgrade a python module fails- it still installs whatever is in the /tmp/pip-build-root/${name}

===

[root@example ~]# pip list | grep bottle
bottle (0.12.7)

python::pip {'bottle':
    pkgname => 'bottle',
    ensure => '0.11.3',
}

/tmp/pip.log (snippet)
Downloading/unpacking bottle==0.11.3
...
Requested bottle==0.11.3, but installing version 0.12.7
...

[root@example ~]# pip list | grep bottle
bottle (0.12.7)

===

Edited modules/python/manifests/pip.ini file

Prepend
        command     => "/bin/rm -rf /tmp/pip-build-root/${name}  ||  ....

Re-ran puppet

[root@example ~]# pip list | grep bottle
bottle (0.11.3)

===

Not sure if this is the best way to solve the problem, but it works.

**Comment by adc-jdiep** [comment]
Found that this issue is with older pip version- 1.3.1.  When I upgraded to newer version, it will upgrade or downgrade the modules correctly.

**Comment by shivapoudel** [comment]
:P
