### ISSUE TITLE
Documentation conflicts itself on whether or not pip must be explictly specified.

### ISSUE THREAD

**Issue by stkerr** [stankevich/puppet-python#160]
Both of these are specified:

"You must explicitly specify pip => true in the python class if you want pip installed. As such, the pip package is now independent of the dev package and so one can exist without the other."

"pip - Install python-pip. Default: true"

**Comment by gene1wood** [comment]
It looks like based on the code that the error is with the first documentation string.

Code for default : https://github.com/stankevich/puppet-python/blob/09967704c152f5fd044ed4ddbc7382ef2e24aea5/manifests/params.pp#L7

**Comment by shivapoudel** [comment]
@gene1wood will you be interested in PR for this documentation fix :)

**Comment by gene1wood** [comment]
Sure thing. I've added PR #217 but it says there are branch conflicts. I've not seen a conflict message like this before and I'm unsure what needs to be done to resolve it.

**Comment by gene1wood** [comment]
Also @shivapoudel you closed this issue after you commented asking for a PR (which may have been on accident)

**Comment by gene1wood** [comment]
Disregard my branch conflict comment, I got confused and have fixed it.

**Comment by shivapoudel** [comment]
Thank! I have merged #217 :tada:
