### ISSUE TITLE
Missing Gunicorn Parameters

### ISSUE THREAD

**Issue by steverecio** [stankevich/puppet-python#167]
Looking at the gunicorn.erb file, there are a handful of gunicorn arguments that are missing. My particular issue is the lack of the --access-logfile and --error-logfile parameters. I could define my own vhost file and start the gunicorn service manually but I'd like to use this puppet module if possible.

Here is a link to my pull request: https://github.com/stankevich/puppet-python/pull/168

**Comment by shivapoudel** [comment]
Close in favour of #168 xD
