### ISSUE TITLE
Unable to use virtualenv in Debian Jessie

### ISSUE THREAD

**Issue by olavmrk** [stankevich/puppet-python#194]
In Debian Jessie the [`python-virtualenv`](https://packages.debian.org/jessie/python-virtualenv) package no longer provides a binary named `virtualenv`. See [Debian bug #752467](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752467) for more information.

Instead of installing `python-virtualenv`, it apperas that one must install the package [`virtualenv`](https://packages.debian.org/jessie/virtualenv), which installs [`python3-virtualenv`](https://packages.debian.org/jessie/python3-virtualenv) and the `/usr/bin/virtualenv` script.

**Comment by ghoneycutt** [comment]
Hi @olavmrk 
Could you send us a PR with this fix?
