### ISSUE TITLE
python-pip requires EPEL on Redhat/CentOs 6 and 7

### ISSUE THREAD

**Issue by gene1wood** [stankevich/puppet-python#196]
First, apologies for opening this issue. There's an existing issue #115 which begins to describe this bug. I'm opening this issue because conversation on #115 has been restricted to contributors by @shivapoudel (which is of course totally fine).

@shivapoudel would it be possible to add a comment to that issue to indicate the status of any efforts to fix that bug or what people should do who use RHEL/CentOS? From the comments in that issue I wasn't able to determine why the conversation had been restricted (there may be background to this issue I'm unaware of).

To clarify the problem (which isn't very specific in #115), under RHEL/CentOS 7, attempting to install python-pip with a stanza like this 

```
  class { 'python' :
    pip => true,
  }
```

will fail because the [system package that this puppet module calls for](https://github.com/stankevich/puppet-python/blob/09967704c152f5fd044ed4ddbc7382ef2e24aea5/manifests/install.pp#L60) isn't part of the base RHEL/CentOS packages, but instead part of [EPEL](https://fedoraproject.org/wiki/EPEL).

A solution to this problem (which I'll try to PR) would be to include the [stahnma-epel](https://forge.puppetlabs.com/stahnma/epel) puppet module as a dependency in the [metadata.json](https://github.com/stankevich/puppet-python/blob/09967704c152f5fd044ed4ddbc7382ef2e24aea5/metadata.json#L43-L48). The nice thing about the `stahnma-epel` puppet module is that it only takes effect on [RHEL derivatives](https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux_derivatives) and [does nothing on other operating systems](https://github.com/stahnma/puppet-module-epel/blob/7322b80c268087bc4b967a9a6ca29923853971f8/manifests/init.pp#L132-L134).

**Comment by gene1wood** [comment]
Some details about this

Package | OS | Source
--- | --- | ---
python-pip | RHEL/CentOS 6 | EPEL
python-virtualenv | RHEL/CentOS 6 | EPEL
python-pip | RHEL/CentOS 7 | EPEL
python-virtualenv | RHEL/CentOS 7 | base

**Comment by shivapoudel** [comment]
@gene1wood You can submit the PR for this :)
