### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ghoneycutt** [stankevich/puppet-python#206]
Hi,

Could you please release a new tag?

Thanks,
-g

**Comment by shivapoudel** [comment]
@stankevich version bump :)

**Comment by ghoneycutt** [comment]
Modulefile should be deprecated. Whenever a bugfix or a feature is merged to master, a tag should be made.

**Comment by ghoneycutt** [comment]
Opened PR #208 to deprecate Modulefile.

**Comment by shivapoudel** [comment]
:heart:

**Comment by shivapoudel** [comment]
@stankevich `Modulefile` is deprecated in #209 so only update version for `metadata.json`

**Comment by stankevich** [comment]
Done.
