### ISSUE TITLE
virtualenv does not use SCL path from environment

### ISSUE THREAD

**Issue by seblau** [stankevich/puppet-python#212]
We have to use a alternative python2.7 installation via RedHat SCL. Is there a possibility to specify the path of the python executable for python::virtualenv? virtualenv.py uses the PATH env variable to discover the python binary. Unfortunately exported paths via Exec do not affect the PATH within the puppet run.

**Comment by seblau** [comment]
The following `path`-option provided by `python::virtualenv` solved my problem. First just looked at the readme which is incomplete, completing the README.md would be helpful.

###### path
* Specifies the PATH variable. Default: [ '/bin', '/usr/bin', '/usr/sbin' ]

**Comment by shivapoudel** [comment]
@seblau done https://github.com/stankevich/puppet-python/commit/48202f1690e40d1d673373b25c72a193ee1d5482
