### ISSUE TITLE
Pip install runs on every puppet run.

### ISSUE THREAD

**Issue by supereman16** [stankevich/puppet-python#218]
On every run of my puppet agent, it runs a pip install, both when I have

```
ensure => present,
```

or,

```
ensure => latest,
```

There has to be a better way to check if it's already the latest version or installed, without just running and Exec for `pip install package` or `pip install --upgrade package`. It takes up a lot of time in the agent's run when I'm installing a lot of packages.

**Comment by ekohl** [comment]
Not to mention that your host will stay in active instead of converging to a stable state.

**Comment by igalic** [comment]
which version of the module are you using, @supereman16 / @ekohl ?

**Comment by tremblaysimon** [comment]
If we don't talk about #193, I think there is sometimes a "strange" behavior when a package has just been updated on PyPI. The pip search package_name command doesn't return the real latest version. I don't know how pip search works but after a couple of minutes the information is updated and the behavior will be the right one (since in pip.pp it uses pip search command).

**Comment by ekohl** [comment]
@igalic 1.9.5 here.

I'm wondering if in my case I can blame it on using ```sentry[postgres]```, pip freeze not reporting that back and ```$grep_regex``` doesn't simplify it to ```sentry```. One can also wonder if that's desired because when a user changes the package from ```sentry``` to ```sentry[postgres]``` will report as done while in fact it isn't.

**Comment by adamcstephens** [comment]
Have you checked your call to python::pip ? pip will install a package with a different case, but the grep in the the definition will always fail so puppet will try and reinstall it.

**Comment by ekohl** [comment]
@adamcstephens I think that's exactly the problem. However, when you simplify ```sentry[postgres]``` to ```sentry``` it becomes impossible to change your manifest from the latter to the former.

**Comment by jordigg** [comment]
I have the same problem but just for one package (I'm just installing two of them). I'm using the following code:

```
#install python + pip
	class { 'python' :
		version 	=> 'system',
		pip 		=> 'present',
		dev			=> 'absent',
		virtualenv	=> 'absent',
		gunicorn	=> 'absent',
		require		=> Exec['apt-update'],
	}

	#install python semantic_version
	python::pip { 'semantic_version' :
	    pkgname	=> 'semantic_version',
	    ensure	=> 'present',
	    require	=> Class['python'],
	}

	#install python sphinx
	python::pip { 'sphinx' :
		pkgname	=> 'sphinx',
		ensure	=> 'present',
		require	=> Class['python'],
	}
```
`semantic_version` gets reinstalled on every run, `sphinx` doesn't. Any clues why semantic_version keeps being reinstalled? Running `pip install semantic_version` and `pip install sphinx` I get the same response `Requirement already up-to-date ...`

**Comment by adamcstephens** [comment]
hyphen != underscore:

```
❯ pip freeze | grep semantic
semantic-version==2.4.2
```

**Comment by jordigg** [comment]
My bad... I don't know were I saw that the package was names with an underscore... New to Python and pip so because it was installing just fine I didn't see that mistake. Thanks so much @adamcstephens

**Comment by xaque208** [comment]
I'm running into this as well, though not trying to install any pip packages yet.  Simply using the pip provider on the python class look for the incorrect path of pip here: https://github.com/stankevich/puppet-python/blob/master/manifests/install.pp#L74

**Comment by gdubicki** [comment]
Same here for both 1.7.16 and 1.9.1 versions with the following code:

```
python::pip { 'pip':
    ensure     => '8.1.0',
    pkgname    => 'pip',
    virtualenv => $::myapp::virtualenv_path,
}
```

**Comment by xaque208** [comment]
Here is the fork I've been keeping to get out of some oddities in this module, such as this issue: https://github.com/xaque208/puppet-python

**Comment by gdubicki** [comment]
Thanks @xaque208, your fork looks interesting, but I need Puppet 3.8 support.

**Comment by igalic** [comment]
@gdubicki keep in mind that puppet 3.x is eol at the end of the year 
and i really wish i could actually find a link…

**Comment by stankevich** [comment]
See https://github.com/stankevich/puppet-python/pull/390

**Comment by maltewhiite** [comment]
I am having this issue. 
```
$python_packages = ['argparse', 'regex', 'prometheus_client']
  package { $python_packages:
    ensure   => installed,
    provider => pip3,
}
```
causes this every time: 
```
Notice: /Stage[main]/Monitoring/Package[argparse]/ensure: created
Notice: /Stage[main]/Monitoring/Package[prometheus_client]/ensure: created
```
