### ISSUE TITLE
virtualenv broken for python3

### ISSUE THREAD

**Issue by jminuscula** [stankevich/puppet-python#24]
The ppa:fkrull/deadsnakes repository provides new python packages, I am using it to install python3.3

The python version in virtualenv definition does not seem to have any effect, as it is always created with the default python for the 'virtualenv' command. pip is not available for python3 either.

In addition, python3+ provides its own virtualenv —pyvenv—, which should be used.

**Comment by sethcleveland** [comment]
Pull request to support pyvenvs was merged. FYI, When building python3.4, there's a configure flag to install with pip.  Does that exist with python3.3?

ex. 
configure --with-ensurepip=install

**Comment by shivapoudel** [comment]
I couldn't found this bug existence ;)
