### ISSUE TITLE
Unable to install pip using pip provider

### ISSUE THREAD

**Issue by joshuaspence** [stankevich/puppet-python#243]
Pull request #241 made it possible to install `pip` via `pip` with the following manifest:

```
class { 'python':
  ensure => 'present',
  provider  => 'pip',
}
```

This does not quite work as expected, however, because it presents a bootstrapping issue (it is not possible to install `pip` via `pip` if `pip` is not installed).

I'm not sure what the best way to fix this is...

**Comment by shivapoudel** [comment]
@joshuaspence If you could then it's OK else I will be reverting back the changes made :-)

**Comment by joshuaspence** [comment]
Sure, I can figure something out. Did you have any ideas?
