### ISSUE TITLE
pip is installed on every invocation when pip is installed from pip

### ISSUE THREAD

**Issue by lattwood** [stankevich/puppet-python#256]
Not sure what the actual cause is

**Comment by igalic** [comment]
@lattwood can you please post the snippet of code that causes that?

**Comment by lattwood** [comment]
I believe it has to do with no paths being specified for the following commands

https://github.com/stankevich/puppet-python/blob/master/manifests/install.pp#L72-L73

`which` uses the current PATH to locate pip

**Comment by igalic** [comment]
self-fulfilling prophecy…
