### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by lattwood** [stankevich/puppet-python#257]
Possible to get a new version released?

It's blocking https://github.com/StackStorm/puppet-st2/issues/114

**Comment by ghoneycutt** [comment]
Released v1.10.0 - https://github.com/stankevich/puppet-python/releases/tag/1.10.0

**Comment by lattwood** [comment]
:bow:

**Comment by lattwood** [comment]
@ghoneycutt what's involved in getting this on the forge?

**Comment by ghoneycutt** [comment]
@stankevich has to release to the forge, since it is under his account. You can use it without it being on the forge though.

**Comment by lattwood** [comment]
Ah, the module I'm working on (`st2`) gets installed via `puppet module install` :-/

**Comment by ghoneycutt** [comment]
Module development should not care how the module gets installed.. If you are using a standard Puppetfile, then you can just point to github.

**Comment by lattwood** [comment]
The module uses metadata.json for dependencies, possible to get this reopened to put releasing this on the forge on @stankevich's radar? StackStorm/puppet-st2#118

**Comment by stankevich** [comment]
Released 1.10.0. Sorry about the delay!

**Comment by lattwood** [comment]
:cool: thanks!
