### ISSUE TITLE
pip install runs every time for packages with underscores in the name

### ISSUE THREAD

**Issue by rpocase** [stankevich/puppet-python#258]
Pip freeze replaces underscores in package names with with hyphens. The grep regex does not take this into account, so it will always try to install packages with underscores in the package name.

E.g, for websocket_client
$pip freeze
websocket-client==0.32.0

Package name needs to have underscores replaced with hyphens when used in $grep_regex in pip.pp.

**Comment by igalic** [comment]
that's kinda tricky, because it also means modifying the namevar… in a way…

**Comment by rpocase** [comment]
I've got a fix on our local module that I think is pretty safe. I keep meaning to do a pull request. I'll try and get that done this weekend.

**Comment by rpocase** [comment]
@igalic It looks like this got reintroduced in the next commit. Any chance of a new merge with this fix?

**Comment by gdubicki** [comment]
Thanks for catching this, @rpocase . Can you please reopen this ticket as a contributor?
