### ISSUE TITLE
puppet not install the latest version of pip

### ISSUE THREAD

**Issue by twmht** [stankevich/puppet-python#268]
Hi,

I am trying to install latest pip (7.1.2) from puppet 3.8.4.

```
class { 'python' :
    version     => 'system',
    pip         => 'latest',
    dev         => 'latest',
    virtualenv  => 'present',
    gunicorn    => 'present',
 }
```

But it only installed very old version (1.5.4).

Is something wrong?

Thank you!

**Comment by erikanderson** [comment]
This is because the module is installing the `python-pip` package from the package repo. I think it would be good to have an option to use the newest version from here: https://pip.pypa.io/en/stable/installing/ 

I will work on a PR to implement this into the module

**Comment by shivapoudel** [comment]
@erikanderson Thanks for the clearance xD
