### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by prattmic** [stankevich/puppet-python#285]
The virtualenv versioned binaries are not always correct (pypa/virtualenv#851), and it looks like they will be removed in the next version. These binaries are avoided on master ([commit](https://github.com/stankevich/puppet-python/commit/5d4e48c94a5a9cfca22f2ed2c7c495c1fc634b3c)). Could you release a new version to include this change?

**Comment by shivapoudel** [comment]
CC @stankevich :)

**Comment by stankevich** [comment]
Released.
