### ISSUE TITLE
Can't install pip3 with Ubuntu

### ISSUE THREAD

**Issue by ColinHebert** [stankevich/puppet-python#287]
With Ubuntu, the expected value for `version` is `python3` to install python3.

Unfortunately, to decide which version of pip to install, we're checking that the version starts with `3` (which is wrong given that the version is `python3`).

https://github.com/stankevich/puppet-python/blob/1.11.0/manifests/install.pp#L198

**Comment by evidex** [comment]
Hitting this issue too when attempting to install `python3.4` on Ubuntu 14.04. This just seems to be a mismatch between the documentation expecting a version number and `install.pp` using the `version` param to define what package to install.

**Comment by ColinHebert** [comment]
Fixed in #293
