### ISSUE TITLE
how to used pip2.7 as provider in RHEL6

### ISSUE THREAD

**Issue by felipe1982** [stankevich/puppet-python#290]
RHEL6 provides python2.6. IUS repo provides python27 and python27-pip packages. The latter provides `/usr/bin/pip2.7`. How do I get this module to call `/usr/bin/pip2.7` for installing python packages?

**Comment by jyaworski** [comment]
Based on this code:

https://github.com/stankevich/puppet-python/blob/master/manifests/install.pp#L18-L22

It looks like if you set version to be the prefix (IE python27, etc) it may work.

@stankevich this should probably be laid out explicitly in the docs.

**Comment by felipe1982** [comment]
I'm not sure that will work because of silly hard-coded paths ::
https://github.com/stankevich/puppet-python/blob/master/manifests/install.pp#L74



Cheers,
Felipe

**Comment by felipe1982** [comment]
any progress here? I'm stuck using TracyWebTech/puppet-pip until I"m able to use this module to install and utilise pip2.7 on RHEL6

**Comment by roqmoyano** [comment]
+1

**Comment by michaeljoy** [comment]
Honestly all that needs to happen is the pip_env variable needs to allow you to specify pip2 or pip3 and it would pretty much all work just fine. I just ended up building my own defined class that does what I want instead. Sometimes virtual_env isn't necessary, needed, or wanted for system libraries like boto3 installed in python2 on a box that has both (super common problem)
