### ISSUE TITLE
--no-use-wheel renamed to --no-binary :all: in pip 7.0 and newer

### ISSUE THREAD

**Issue by hmpf** [stankevich/puppet-python#309]
This leads to a warning including this string when pip installing:

DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.

**Comment by KlavsKlavsen** [comment]
This is hitting me as well - trying to install puppetboard :(

**Comment by smaslennikov** [comment]
Actually, it seems `9.0.1` doesn't have `--no-binary` either:

```bash
$ pip --version
pip 9.0.1 from ...
$ pip --no-use-wheel
Usage:   
  pip <command> [options]

no such option: --no-use-wheel
$ pip --no-binary :all:
Usage:   
  pip <command> [options]

no such option: --no-binary
```

**Comment by chgarling** [comment]
We are affected to. I am working on a pull request to fix this.

**Comment by smaslennikov** [comment]
@chgarling I'm working on figuring out how to fix this as well, for some reason in puppet pip isn't happy with `--no-binary` for me

**Comment by chgarling** [comment]
I made some tests on CentOS 7 without puppet and this module. If you create a new virtualenv with e.g. "virtualenv testenv" pip version 1.4.1 is installed. Because of pip is < 7.0 it does not understand --no-binary. Correct me if I am wrong with that. In my opinion the steps should be:
1. Create virtualenv
2. pip install --upgrade pip
3. all the other stuf

**Comment by chgarling** [comment]
With this changes to the python::virtualenv class it applies without errors:
`diff --git a/manifests/virtualenv.pp b/manifests/virtualenv.pp
index 459b339..1d328f7 100644
--- a/manifests/virtualenv.pp
+++ b/manifests/virtualenv.pp
@@ -159,7 +159,7 @@ define python::virtualenv (
     $pip_cmd = "${python::exec_prefix}${venv_dir}/bin/pip"
 
     exec { "python_virtualenv_${venv_dir}":
-      command     => "true ${proxy_command} && ${virtualenv_cmd} ${system_pkgs_flag} -p ${python} ${venv_dir} && ${pip_cmd} wheel --help > /dev/null 2>&1 && { ${pip_cmd} wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag} \$wheel_support_flag --upgrade pip ${distribute_pkg} || ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag}  --upgrade pip ${distribute_pkg} ;}",
+      command     => "true ${proxy_command} && ${virtualenv_cmd} ${system_pkgs_flag} -p ${python} ${venv_dir} && ${pip_cmd} install --upgrade pip && ${pip_cmd} wheel --help > /dev/null 2>&1 && { ${pip_cmd} wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-binary :all:'; } ; { ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag} \$wheel_support_flag --upgrade pip ${distribute_pkg} || ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag}  --upgrade pip ${distribute_pkg} ;}",
       user        => $owner,
       creates     => "${venv_dir}/bin/activate",
       path        => $path,
@@ -171,7 +171,7 @@ define python::virtualenv (
 
     if $requirements {
       exec { "python_requirements_initial_install_${requirements}_${venv_dir}":
-        command     => "${pip_cmd} wheel --help > /dev/null 2>&1 && { ${pip_cmd} wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag} \$wheel_support_flag -r ${requirements} ${extra_pip_args}",
+        command     => "${pip_cmd} wheel --help > /dev/null 2>&1 && { ${pip_cmd} wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-binary :all:'; } ; ${pip_cmd} --log ${venv_dir}/pip.log install ${pypi_index} ${proxy_flag} \$wheel_support_flag -r ${requirements} ${extra_pip_args}",
         refreshonly => true,
         timeout     => $timeout,
         user        => $owner,
`

**Comment by smaslennikov** [comment]
@chgarling can you paste that in ``` code formating?

**Comment by chgarling** [comment]
First try was formatted as code.

**Comment by smaslennikov** [comment]
Fantastic, thank you @chgarling, I'll give it a try in a second

**Comment by chgarling** [comment]
Which OS are you testing on? CentOS, Debian, SLES?

**Comment by smaslennikov** [comment]
Centos 7

**Comment by chgarling** [comment]
Let me know if you have a result.

**Comment by smaslennikov** [comment]
@chgarling looks like that works fine. No errors, at least

**Comment by chgarling** [comment]
Recently I have no good idea how to handle the python::pip class regarding to the deprecated --no-use-wheel option. As I understand this class can be used with manually created virtualenvs, so the pip version is unknown.

pip <= 1.4.1 has no --no-use-wheel option
pip >= 1.5.0 <= 7.0.0 has the --no-use-wheel option but not --no-binary
pip >= 7.0.0 deprecates the --no-use-wheel option in favour to --no-binary

A variable with the pip version from the specific virtualenv is needed to set the right wheel_support_flag option. But how? Facts are to static in this case, nor?

**Comment by chgarling** [comment]
Recently I have no good idea how to handle the python::pip class regarding to the deprecated --no-use-wheel option. As I understand this class can be used with manually created virtualenvs, so the pip version is unknown.

pip <= 1.4.1 has no --no-use-wheel option
pip >= 1.5.0 <= 7.0.0 has the --no-use-wheel option but not --no-binary
pip >= 7.0.0 deprecates the --no-use-wheel option in favour to --no-binary

A variable with the pip version from the specific virtualenv is needed to set the right wheel_support_flag option. But how? Facts are to static in this case, nor?

**Comment by ghoneycutt** [comment]
There are different versions of pip per virtualenv, right? If so, how do you figure out which version of pip is installed in that virtualenv? Is it possible to specify the pip version when creating a virtualenv?

**Comment by chgarling** [comment]
@ghoneycutt if you use python::virtualenv the latest pip version is installed since my commit. On the other hand you can use the python::pip class with an already available virtualenv, in this case the pip version is unknown.

**Comment by smaslennikov** [comment]
This change should also probably take place in `pip.pp`

**Comment by mikkergimenez** [comment]
It looks like this has been quiet for a while but there's a PR that seems ready to go?

https://github.com/stankevich/puppet-python/pull/366

**Comment by mikkergimenez** [comment]
Does this PR to solve this issue still need more work? This issue could probably use a bump, as it could cause puppet runs to fail on newer versions of pip.

https://github.com/stankevich/puppet-python/pull/366

**Comment by stankevich** [comment]
Fixed in https://github.com/stankevich/puppet-python/pull/388
