### ISSUE TITLE
regex for pip explicit version ( ensure => '1.0a1' ) broken

### ISSUE THREAD

**Issue by whyteks** [stankevich/puppet-python#310]
While attempting to add pip package gsm0338 with version 1.0a1, I noted puppet actually trying and failing to UNinstall this package.

The regular expression here:
https://github.com/stankevich/puppet-python/blob/master/manifests/pip.pp#L150
will not catch a version like 1.0a1, or 0.31.1-1 and will attempt to uninstall the existing version, although this fails. 

I note the Version formats comment here:
https://github.com/stankevich/puppet-python/blob/master/manifests/pip.pp#L213
However, that domain appears to be down, or infected with adware.
Seaching for guidelines, I found this page:
http://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/specification.html
which would appear to suggest that examples such as 1.3a2.dev12 are acceptable

I would submit a patch, but I feel the lack of a patch is probably not the issue. Anyway, It's a simple regex mod, best left up to the developer who chose the current regex.

Question: Is there some political issue that requires packages to use only digits in the version scheme?
On my system, a quick check of pip freeze shows a not insignificant number of packages with version names that would not install with this puppet module.

**Comment by traylenator** [comment]
Also impacting us with https://pypi.python.org/pypi/rucio/1.6.0.post2

**Comment by reguero** [comment]
For your info, I found the regular expression used by pip itself for the operator (==, <=, etc) with the the version of the package requested in line 2293 of /usr/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py
It is as follows
VERSION = re.compile(r"\s*(<=?|>=?|===?|!=|~=)\s*((\w|[-.*_!+])+)").match

**Comment by JamieCressey** [comment]
+1

**Comment by martinjungblut** [comment]
+1

I'm being affected by this issue as well. In my opinion, if you provide a version string yourself, and there's no match for that particular version in PyPI, it's your problem. I don't feel like this module should try to enforce a versioning scheme, I feel it should do what I mean, which is try to grab the version I told it to.
