### ISSUE TITLE
EPEL7 python-pip package is called python2-pip; puppet-python won't recognize that it is installed

### ISSUE THREAD

**Issue by talisto** [stankevich/puppet-python#346]
In EPEL7, the `python-pip` package is called `python2-pip`.  It is aliased to `python-pip`, so it can be installed with `yum install python-pip`, but then running `yum list python-pip` returns `No matching Packages`.  

This causes some problems when `puppet-python` tries to install the pip package:

```
Error: Execution of '/bin/yum -d 0 -e 0 -y list python-pip' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Python::Install/Package[pip]/ensure: change from absent to present failed: Execution of '/bin/yum -d 0 -e 0 -y list python-pip' returned 1: Error: No matching Packages to list
Notice: /Stage[main]/Python/Anchor[python::end]: Dependency Package[pip] has failures: true
Warning: /Stage[main]/Python/Anchor[python::end]: Skipping because of failed dependencies
```

Is there a workaround for this?  I tried to figure out if there was a way that I could force `puppet-python` to look for `python2-pip` instead of `python-pip` but I couldn't see that as a configurable option.

I'm running CentOS 7.2.

**Comment by talisto** [comment]
I fixed this by setting `python::version` to `python27` and `python::provider` to `scl`.

**Comment by ghoneycutt** [comment]
Sounds like we need to change the name of the package.
