### ISSUE TITLE
python-pip has been renamed to python2-pip on el7 epel repo

### ISSUE THREAD

**Issue by david-caro** [stankevich/puppet-python#348]
I found this week that the python-pip package is not available anymore for el7 on epel anymore, it has been replaced by python2-pip. That makes the module fail trying to check if it's installed as puppet does not really handle well the 'obsoletes' and similar rpm headers.

**Comment by danielbenzvi** [comment]
It seems python2-pip was renamed back to python-pip.

**Comment by Reamer** [comment]
I can confirm that it was renamed back to python-pip

**Comment by ghoneycutt** [comment]
Sounds like this is no longer an issue since it was solved by the EPEL folks renaming the package. Please re-open if this is not the case. Thanks everyone!
