### ISSUE TITLE
travis build failures since december?

### ISSUE THREAD

**Issue by 7yl4r** [stankevich/puppet-python#372]
The last passing pull request was  Dec 23, 2016. I re-ran the last passing set of tests on master ([Commit 0a03cf2](https://travis-ci.org/stankevich/puppet-python/builds/184070736)) and got all failures ([rerun of Commit 0a03cf2](https://travis-ci.org/USF-IMARS/puppet-python/builds/230863771)).

Something has changed in the travis environment. [Maybe due to the release of rvm 2.4?](https://github.com/travis-ci/travis-ci/issues/7077). I will be pursuing a fix so please comment if you have ideas. Best lead currently is `before_install:  - gem install bundler` ([ref](https://github.com/travis-ci/travis-ci/issues/5239)).

**Comment by flokli** [comment]
@7yl4r: This can be closed now, right?
