### ISSUE TITLE
Manage Python related .dotfiles (for a user)

### ISSUE THREAD

**Issue by igalic** [stankevich/puppet-python#87]
There are a handful of Python related dotfiles, which don't seem to have a global option in /etc (or if they do, it's not documented)

In our very old fork of this module, we have a defined type python::dotfiles, which manages:

* .pypirc
* .pydistutils.cfg
* .pip
* .pip/pip.conf

The main reason why we need this is because so we can direct our jenkins builds against our internal PyPy repository.

Is there any interest for such an extension to this module?

**Comment by igalic** [comment]
i have now solved this issue with a private (general) defined type (in a profile)
```puppet
define profile::python::dotfile (
  $ensure   = 'present',
  $filename = $title,
  $owner    = 'root',
  $group    = 'root',
  $mode     = '0644',
  $config   = {},
) {
  $parent_dir = dirname($filename)

  exec { "create ${title}'s parent dir":
    command => "install -o ${owner} -g ${group} -d ${parent_dir}",
    creates => $parent_dir,
  }

  file { $filename:
    ensure  => $ensure,
    owner   => $owner,
    group   => $group,
    content => template("${module_name}/inifile.erb"),
    require => Exec["create ${title}'s parent dir"],
  }
}
```

the template is simply:
```erb
# this file is managed by puppet
<%- @config.map do |section,conf| -%>
[<%= section -%>]
<%-   conf.map do |key,value| -%>
<%= key %> = <%= value %>

<%-   end -%>
<%- end -%>
```

**Comment by shivapoudel** [comment]
@igalic it will be better if you submit the Pull Request xD

**Comment by igalic** [comment]
okay!
